# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  # contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
# ko:
#  languageCode: ko
#  contentDir: content/ko
#  title: Chinese website title...
#  params:
#    description: Site description in Korean...
#  menu:
#    main:
#      - name: About
#        url: '#about'
#        weight: 1
